### ISSUE TITLE
"No more keys found" - after running e3.py on a jediflash.bin file

### ISSUE THREAD

**Issue by x0rtes** [dogtopus/e3pp#4]
Hello @dogtopus  , Im trying to generate the files needed to passinglink to authenticate ds4, I tried running your e3.py this way:

python e3.py jedi_flash.bin -o [some destination] --gen-passinglink-ds4key

But only get "No more keys found" as response.

What should I do to get ds4.der ds4.sig and ds4.serial?

Also I tried to generate manually the ds4.sig and ds4.serial via HxD and slicing the adresses on your code, I think they are right, but I dont know how to generate the ds4.der

Thanks in advance!

**Comment by dogtopus** [comment]
Please use `jedi_crypto.py` for this purpose. e3 was not built for extracting stuff from the DS4 firmware. You may need to do some modifications in order to make it dump DER file though.

**Comment by x0rtes** [comment]
Thanks for your answer!

Ok, I was able to extract the .der via a mod of jedi_crypto.py

I thought your program was able to do this because of that comment:

> Dumps information of a DS4 key block and (optionally) extracts it from
> a binary file. Also works with raw key blocks extracted by
> e.g. jedi_crypto.py.

Now I'm curious... What exactly is the format of the key block your program use?

**Comment by dogtopus** [comment]
> Thanks for your answer!
> 
> Ok, I was able to extract the .der via a mod of jedi_crypto.py
> 
> I thought your program was able to do this because of that comment:
> 
> > Dumps information of a DS4 key block and (optionally) extracts it from
> > a binary file. Also works with raw key blocks extracted by
> > e.g. jedi_crypto.py.
> 
> Now I'm curious... What exactly is the format of the key block your program use?

It should be the exact same format as an unscrambled DS4 key block. DS4 incorporates a simple obfuscation method to cover up the key block to probably stop those who just look for plaintext. e3 does not do the unscrambling, instead it only looks for the plaintext because that's what some knockoff controllers use.

You can also use jedi_crypto to extract the unscrambled key block and generate passinglink header/DER formatted public key from it. I would recommend the DER method since passinglink is moving away from headers.

PS: `ds4.sig` and `ds4.serial` matches e3's `ds4.ds4id.sig` and `ds4.ds4ser` if you didn't know already

**Comment by x0rtes** [comment]
Thanks! I was able to create the DER format(Public and Private), then I searched in jedi_crypto code where it extracts sig and serial, and tried to copy these parts on the HEX via HxD.

This way I made:
Hex generated serial(16b) -> ds4.serial
Hex generated sig(256b) -> ds4.sig
PRIVATE DER generated by jedi_crypto-mod.py -> ds4.der

I don't know if all these files are right, but still I can't know for sure because of this issue: https://github.com/passinglink/passinglink/issues/15#issuecomment-827834112

Again thanks for the help!

Edit: I have the Public DER as well, but I don't know if must be used.

**Comment by x0rtes** [comment]
I was able to make it work, thanks for your help. I will close the issue.

**Comment by InfraredAces** [comment]
> Thanks for your answer!
> 
> Ok, I was able to extract the .der via a mod of jedi_crypto.py
> 
> I thought your program was able to do this because of that comment:
> 
> > Dumps information of a DS4 key block and (optionally) extracts it from
> > a binary file. Also works with raw key blocks extracted by
> > e.g. jedi_crypto.py.
> 
> Now I'm curious... What exactly is the format of the key block your program use?

What modifications did you make to jedi_crypto.py? I am running into an issue where it just tells me that the MAC Check failed and I am unable to determine what went wrong.
